#!/usr/bin/env node

/**
 * Sync the fallback docs registry from the live GitHub API.
 *
 * Usage:
 *   GITHUB_PAT=ghp_xxx node scripts/sync-docs.mjs
 *
 * This updates src/lib/fallback-registry.ts with the latest repos and docs
 * discovered from your GitHub account. Run this periodically or after adding
 * new repos/docs to keep the fallback registry up to date.
 */

const OWNER = process.env.NEXT_PUBLIC_GITHUB_OWNER ?? "";
const PAT = process.env.GITHUB_PAT ?? "";

if (!PAT) {
  console.error("Error: GITHUB_PAT environment variable is required.");
  console.error("Usage: GITHUB_PAT=ghp_xxx node scripts/sync-docs.mjs");
  process.exit(1);
}

const headers = {
  Accept: "application/vnd.github+json",
  Authorization: `Bearer ${PAT}`,
  "X-GitHub-Api-Version": "2022-11-28",
};

async function fetchJSON(url) {
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`${res.status}: ${url}`);
  return res.json();
}

async function main() {
  console.log(`Fetching repos for ${OWNER}...`);

  // Fetch all public repos
  let repos = [];
  let page = 1;
  while (true) {
    const batch = await fetchJSON(
      `https://api.github.com/users/${OWNER}/repos?per_page=100&page=${page}&sort=updated&type=public`
    );
    repos.push(...batch);
    if (batch.length < 100) break;
    page++;
  }

  repos = repos.filter((r) => !r.fork && !r.archived && !r.private);
  console.log(`Found ${repos.length} public repos.`);

  // Discover docs in each repo
  const configs = [];
  for (const repo of repos) {
    process.stdout.write(`  Scanning ${repo.name}...`);
    try {
      const tree = await fetchJSON(
        `https://api.github.com/repos/${OWNER}/${repo.name}/git/trees/${repo.default_branch}?recursive=1`
      );

      const mdFiles = tree.tree.filter(
        (item) =>
          item.type === "blob" &&
          item.path.startsWith("docs/") &&
          item.path.endsWith(".md")
      );

      if (mdFiles.length === 0) {
        console.log(" no docs/");
        continue;
      }

      // Group by folder
      const folders = new Map();
      for (const file of mdFiles) {
        const parts = file.path.split("/");
        const folder = parts.length > 2 ? parts.slice(0, -1).join("/") : "docs";
        if (!folders.has(folder)) folders.set(folder, []);
        folders.get(folder).push(file.path);
      }

      const docFolders = Array.from(folders.entries())
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([name, files]) => ({ name, files: files.sort() }));

      const name = repo.name
        .replace(/^Dotnet/, ".NET ")
        .replace(/([a-z])([A-Z])/g, "$1 $2")
        .replace(/[-_]/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase())
        .replace(/\. Net/g, ".NET")
        .trim();

      configs.push({
        repo: repo.name,
        name,
        description: repo.description ?? `${repo.name} documentation`,
        language: repo.language ?? "Unknown",
        branch: repo.default_branch,
        topics: repo.topics ?? [],
        htmlUrl: repo.html_url,
        files: mdFiles.length,
        docFolders,
      });

      console.log(` ${mdFiles.length} docs`);
    } catch (e) {
      console.log(` error: ${e.message}`);
    }
  }

  configs.sort((a, b) => a.name.localeCompare(b.name));
  console.log(`\nFound ${configs.length} repos with docs.`);

  // Generate fallback registry file
  let output = `/**
 * Static fallback registry — auto-generated by scripts/sync-docs.mjs
 * Last synced: ${new Date().toISOString()}
 *
 * Run: GITHUB_PAT=ghp_xxx node scripts/sync-docs.mjs
 */

import type { RepoDocsConfig } from "@/lib/github";

function f(name: string, files: string[]): { name: string; files: { path: string; title: string; size: number }[] } {
  return {
    name,
    files: files.map((p) => ({
      path: p,
      title: p.split("/").pop()!.replace(/\\.md$/, "").replace(/^\\d+-/, "").replace(/[-_]/g, " ").replace(/\\b\\w/g, (c) => c.toUpperCase()),
      size: 5000,
    })),
  };
}

export const FALLBACK_REGISTRY: RepoDocsConfig[] = [\n`;

  for (const config of configs) {
    const folders = config.docFolders
      .map((folder) => {
        const files = folder.files.map((f) => `"${f}"`).join(",");
        return `f("${folder.name}", [${files}])`;
      })
      .join(", ");

    output += `  { repo: "${config.repo}", name: "${config.name}", description: ${JSON.stringify(config.description)}, language: "${config.language}", branch: "${config.branch}", topics: ${JSON.stringify(config.topics)}, htmlUrl: "${config.htmlUrl}", updatedAt: "", stars: 0, docs: [${folders}] },\n`;
  }

  output += `];\n`;

  const fs = await import("fs");
  const path = await import("path");
  const outPath = path.join(process.cwd(), "src/lib/fallback-registry.ts");
  fs.writeFileSync(outPath, output);
  console.log(`\nWritten to ${outPath}`);
  console.log("Done! Commit and push to update the fallback registry.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
